services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: onboard-week2-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped